jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION:900000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}

server:
  port: 8081

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:auth-db}:${DB_PORT:5432}/${DB_NAME:auth}
    username: ${DB_USERNAME:auth_user}
    password: ${DB_PASSWORD:auth_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: create-drop
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: ${LIQUIBASE_CONTEXTS:}
    default-schema: public
  
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: auth-service

logging:
  level:
    com.paypulse: DEBUG
    org.springframework.security: DEBUG
    org.liquibase: INFO
    org.springframework.data.redis: DEBUG
    org.springframework.retry: DEBUG
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","logger":"%c{1.}","traceId":"%X{traceId}","spanId":"%X{spanId}","userId":"%X{userId}","message":"%m","thread":"%t"}'
    file: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","logger":"%c{1.}","traceId":"%X{traceId}","spanId":"%X{spanId}","userId":"%X{userId}","message":"%m","thread":"%t"}'
  file:
    name: logs/auth-service.log
    max-size: 10MB
    max-history: 30
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB


rate-limit:
  max-requests-per-minute: ${RATE_LIMIT_MAX_REQUESTS:100}
  window-size-minutes: ${RATE_LIMIT_WINDOW:1}
  enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true