server:
  port: 8084

spring:
  application:
    name: notification-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:notification-db}:${DB_PORT:5432}/${DB_NAME:notification}
    username: ${DB_USERNAME:notif_user}
    password: ${DB_PASSWORD:notif_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: ${LIQUIBASE_CONTEXTS:}
    default-schema: public
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:notification-group}
      auto-offset-reset: earliest

jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.paypulse: DEBUG
    org.liquibase: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true