global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'wallet-service'
    static_configs:
      - targets: ['wallet-service:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s 